### ISSUE TITLE
How to get the access token

### ISSUE THREAD

**Issue by maddymathan** [AdrianVillamayor/Whatsapp-Api#3]
Could you please share the procedure to get the access token to use this api

**Comment by AdrianVillamayor** [comment]
Hi @maddymathan,

In order to send a message and get an access_token for the webhooks you have to follow the guidelines in the Whatsapp Business Platform documentation.

See Required Assets section=> [https://developers.facebook.com/docs/whatsapp/business-management-api/get-started](https://developers.facebook.com/docs/whatsapp/business-management-api/get-started)

Also I have updated the README.md with the link.

If you have any problems and/or doubts, let me know.

**Comment by maddymathan** [comment]
require_once 'vendor/autoload.php';
use Adrii\Whatsapp\Whatsapp;
	
$graph_version    = "v14.0";
$phone_number_id  = "105802848942091";
$access_token     = "EAAGSBUkK7tsBAB1jHIm5MN3LfnpjOprwrIhjhTowOS8grQeeO8EYCJ1qVDym00KioYQnfMQk5pJMJ3OndrCZCos6of7s1SendmqeNVHA8ZAkQpjwvRb0yfyEyph4PGDFwxuR3aRt4EAhqowNZBKHkzBJYZAOeugBBUOpZAnyvTi8g9ggDCQAMTVRJLsAs8diQ4QMQGbchaQZDZD";
$recipient_id     = "918248175266";

$ws = new Whatsapp($phone_number_id, $access_token, $graph_version);
	
$ws->send_message()->text("Aloha 🍍", $recipient_id);

**Comment by maddymathan** [comment]
I have got the access token and when I tried to configure it in the PHP and try to reload the PHP in the browser no error message was displayed and no WhatsApp message to the recipient.  Please help to make it

**Comment by AdrianVillamayor** [comment]
I am checking and right now the messaging service is either recovering from an outage or is experiencing some disruption, at least in my region.

Returns an HTTP code 500 with  his JSON.
```
{
    "error": {
        "message": "(#131000) Something went wrong",
        "type": "OAuthException",
        "code": 131000,
        "error_data": {
            "messaging_product": "whatsapp",
            "details": "Something went wrong"
        },
        "error_subcode": 2494002,
        "fbtrace_id": "AdGVAeyKuL21J0F8DqEAuot"
    }
}
```

You can check it in this url => [https://developers.facebook.com/docs/whatsapp/support-api-status-page/](https://developers.facebook.com/docs/whatsapp/support-api-status-page/)


Otherwise the code is fine but I recommend you to start the tests with templates because the text messages can give error if a user has not responded for a long time.


To check that it is not a bug in the Whatsapp system or in the code, use the test in the same platform or the curl generated in the same platform. I add an example with the data you have put above (check that the token is still active and that the data is correct).

```
curl -i -X POST \
  https://graph.facebook.com/v15.0/105802848942091/messages \
  -H 'Authorization: Bearer EAAGSBUkK7tsBAB1jHIm5MN3LfnpjOprwrIhjhTowOS8grQeeO8EYCJ1qVDym00KioYQnfMQk5pJMJ3OndrCZCos6of7s1SendmqeNVHA8ZAkQpjwvRb0yfyEyph4PGDFwxuR3aRt4EAhqowNZBKHkzBJYZAOeugBBUOpZAnyvTi8g9ggDCQAMTVRJLsAs8diQ4QMQGbchaQZDZD' \
  -H 'Content-Type: application/json' \
  -d '{ "messaging_product": "whatsapp", "to": "your-number", "type": "template", "template": { "name": "hello_world", "language": { "code": "en_US" } } }'
```

If you have any problems or doubts, let me know
